import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { EcommerceLayout } from "./components/ecommerce-layout";
import { TooltipProvider } from "@/components/ui/tooltip";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <TooltipProvider>
          <EcommerceLayout>
            {children}
          </EcommerceLayout>
        </TooltipProvider>
      </body>
    </html>
  );
}
